import { paneView } from "./views.js";
export const pane = paneView.parse({
  id: JSON.stringify(["loom-test#1", "%2"]),
  hostGeneration: "loom-test#1",
  sessionName: "research",
  windowId: "@1",
  paneId: "%2",
  sessionId: "$1",
  windowName: "shell",
  spaceTitle: null,
  tabTitle: null,
  paneTitle: null,
  command: "sh",
  startCwd: "/tmp",
  branch: null,
  dead: false,
  exitStatus: null,
  attachedClients: 2,
  unavailable: false,
  taskId: null,
  runId: null,
  taskName: null,
  issueKey: null,
  taskStage: null,
  role: null,
  provider: null,
  status: null,
  attention: false,
});
